server:
    context-path: /nla_sample

spring: 
    main:
        banner-mode: "off"       
    datasource:
        platform: h2

logging: 
    level: 
        org: 
            springframework: ERROR
