CREATE TABLE USERS(ID BIGINT PRIMARY KEY AUTO_INCREMENT
		, FIRST_NAME VARCHAR(30)
		, LAST_NAME VARCHAR(30)
		, PHONE_NUMBER VARCHAR(30)
		, EMAIL_ADDRESS VARCHAR(320)	
		);
		
CREATE TABLE BOOKS(ID BIGINT PRIMARY KEY AUTO_INCREMENT
		, TITLE VARCHAR(30)
		, AUTHOR VARCHAR(30)
		, ISBN VARCHAR(30)
		, STATUS VARCHAR(30)
		, USER BIGINT
		);